// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using REIGN.Data;

#nullable disable

namespace REIGN.Data.Migrations
{
    [DbContext(typeof(ReignDbContext))]
    partial class ReignDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("REIGN.Data.Models.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AppointmentTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalCalendarEventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("REIGN.Data.Models.ConversationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOwnerOverride")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("ConversationMessages");
                });

            modelBuilder.Entity("REIGN.Data.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConversationStatus")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentIntent")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HumanOverrideActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("HumanOverrideAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IntentHistory")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastCustomerMessageAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastIntent")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemorySummary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PendingServiceName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TurnCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("REIGN.Data.Models.IntegrationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("AccessTokenExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Provider")
                        .IsUnique();

                    b.ToTable("IntegrationTokens");
                });

            modelBuilder.Entity("REIGN.Data.Models.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9c1a1111-1111-4111-8111-111111111111"),
                            Active = true,
                            DurationMinutes = 20,
                            Name = "Quick Visit",
                            Price = 150m
                        },
                        new
                        {
                            Id = new Guid("9c1a2222-2222-4222-8222-222222222222"),
                            Active = true,
                            DurationMinutes = 30,
                            Name = "Half Hour",
                            Price = 300m
                        },
                        new
                        {
                            Id = new Guid("9c1a3333-3333-4333-8333-333333333333"),
                            Active = true,
                            DurationMinutes = 60,
                            Name = "Hour",
                            Price = 500m
                        });
                });

            modelBuilder.Entity("REIGN.Data.Models.ServiceRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceRecommendations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9c1aaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa"),
                            Active = true,
                            Recommendation = "Customer is asking about a Quick Visit (QV): $150, less than 30 minutes.",
                            ServiceId = new Guid("9c1a1111-1111-4111-8111-111111111111"),
                            Trigger = "quick"
                        },
                        new
                        {
                            Id = new Guid("9c1bbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb"),
                            Active = true,
                            Recommendation = "Customer is asking about a Half Hour appointment (HH): $300, 30 minutes.",
                            ServiceId = new Guid("9c1a2222-2222-4222-8222-222222222222"),
                            Trigger = "half"
                        },
                        new
                        {
                            Id = new Guid("9c1ccccc-cccc-4ccc-8ccc-cccccccccccc"),
                            Active = true,
                            Recommendation = "Customer is asking about an Hour appointment (HR): $500, 60 minutes.",
                            ServiceId = new Guid("9c1a3333-3333-4333-8333-333333333333"),
                            Trigger = "hour"
                        });
                });

            modelBuilder.Entity("REIGN.Data.Models.Appointment", b =>
                {
                    b.HasOne("REIGN.Data.Models.Customer", "Customer")
                        .WithMany("Appointments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("REIGN.Data.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("REIGN.Data.Models.ConversationMessage", b =>
                {
                    b.HasOne("REIGN.Data.Models.Customer", "Customer")
                        .WithMany("Messages")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("REIGN.Data.Models.ServiceRecommendation", b =>
                {
                    b.HasOne("REIGN.Data.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("REIGN.Data.Models.Customer", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
